### ISSUE TITLE
'Network' object has no attribute '_loss'`

### ISSUE THREAD

**Issue by zihaozhang9** [JaminFong/darts#2]
Hello! Have you completed the code?
I cloned your project. I tried to use multiple gpus training and received the following log.

> pytorch 0.4

log：
`Traceback (most recent call last):
  File "train_search.py", line 202, in <module>
    main() 
  File "train_search.py", line 127, in main
    train_acc, train_obj = train(train_queue, valid_queue, model, architect, criterion, optimizer, lr)
  File "train_search.py", line 155, in train
    architect.step(input, target, input_search, target_search, lr, optimizer, unrolled=args.unrolled)
  File "/darts-multi_gpu/cnn/architect.py", line 36, in step
    self._backward_step_unrolled(input_train, target_train, input_valid, target_valid, eta, network_optimizer)
  File "/darts-multi_gpu/cnn/architect.py", line 48, in _backward_step_unrolled
    unrolled_model = self._compute_unrolled_model(input_train, target_train, eta, network_optimizer)
  File "/darts-multi_gpu/cnn/architect.py", line 23, in _compute_unrolled_model
    loss = self.model.module._loss(input, target)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))
AttributeError: 'Network' object has no attribute '_loss'`

**Comment by JaminFong** [comment]
@zihaozhang9 I have not implemented the `--unrolled` version on multi gpus. You could modify it following the first-order version I have implemented.

**Comment by zihaozhang9** [comment]
> @ zihaozhang9我还没有`--unrolled`在multi gpus上实现这个版本。您可以按照我实现的第一个版本修改它。
ok!very thanks~
